// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BlackEmptyLayout from "../../Layouts/BlackEmptyLayout/BlackEmptyLayout.bs.js";

function $$default(param) {
  console.log("test: component");
  return React.createElement(BlackEmptyLayout.make, {
              children: null
            }, React.createElement("h2", {
                  className: "text-2xl"
                }, "MINHA DESPEDIDA DE SOLTEIRO"), React.createElement("h2", {
                  className: "text-2xl"
                }, "DIA: 11/03/23"), React.createElement("h2", {
                  className: "text-2xl"
                }, "HORARIO: 15:00"), React.createElement("h2", {
                  className: "text-2xl"
                }, "LOCAL: TATUAPE"));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
