// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BlackEmptyLayout from "../../Layouts/BlackEmptyLayout/BlackEmptyLayout.bs.js";

function $$default(param) {
  console.log("test: component");
  return React.createElement(BlackEmptyLayout.make, {
              children: "Pag despedida"
            });
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
