// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BlackEmptyLayout from "../../Layouts/BlackEmptyLayout/BlackEmptyLayout.bs.js";

function $$default(param) {
  console.log("test: component");
  return React.createElement(BlackEmptyLayout.make, {
              children: null
            }, React.createElement("h2", {
                  className: "text-2xl"
                }, "DESPEDIDA DE SOLTEIRO DO BRAGA"), React.createElement("h2", {
                  className: "text-2xl"
                }, "DIA: 11/03/23"), React.createElement("h2", {
                  className: "text-2xl"
                }, "HORARIO: 16:00"), React.createElement("h2", {
                  className: "text-2xl"
                }, "LOCAL: Rancho Urbano Rua Azevedo Soares, 604 - Vila Gomes Cardim"), React.createElement("h2", {
                  className: "text-2xl text-blue-900"
                }, "TEM VALLET NO LOCAL"));
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
