// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function BlackEmptyLayout(props) {
  var match = React.useState(function () {
        return 1.0;
      });
  var setId = match[1];
  var id = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setBalloons = match$1[1];
  var tick = function (param) {
    Curry._1(setBalloons, (function (old) {
            return Belt_Array.concat(old, [{
                          id: String(id)
                        }]);
          }));
    Curry._1(setId, (function (param) {
            return Js_math.random_int(1, 999999999) / 999999 | 0;
          }));
  };
  setInterval(tick, 5000);
  var allBallos = Belt_Array.map(match$1[0], (function (balloon) {
          return React.createElement("div", {
                      key: balloon.id,
                      className: "w-1"
                    });
        }));
  return React.createElement("main", {
              className: "w-full h-full flex flex-col items-center justify-center\n  bg-black text-white relative"
            }, allBallos, React.createElement("section", {
                  className: "z-10"
                }, props.children));
}

var make = BlackEmptyLayout;

export {
  make ,
}
/* react Not a pure module */
