// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function BlackEmptyLayout(props) {
  console.log("test: layout");
  return React.createElement("main", {
              className: "w-full h-full"
            }, props.children);
}

var make = BlackEmptyLayout;

export {
  make ,
}
/* react Not a pure module */
