// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ActiveLink from "./ActiveLink/ActiveLink.bs.js";

function Navbar(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsOpen = match[1];
  var isOpen = match[0];
  var iconMenuClassNames = isOpen ? "hidden" : "block";
  var dropdownMenuClassNames = isOpen ? "transition ease-out duration-200" : "transition ease-in duration-75";
  return React.createElement("nav", {
              className: "bg-white shadow"
            }, React.createElement("div", {
                  className: "mx-auto max-w-7xl px-2 sm:px-6 lg:px-8"
                }, React.createElement("div", {
                      className: "relative flex h-16 justify-between"
                    }, React.createElement("div", {
                          className: "absolute inset-y-0 left-0 flex items-center sm:hidden"
                        }, React.createElement("button", {
                              "aria-expanded": false,
                              "aria-controls": "mobileMenu",
                              className: "inline-flex items-center justify-center rounded-md\n        p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500\n        focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
                            }, React.createElement("span", {
                                  className: "sr-only"
                                }, "Open main menu"), React.createElement("svg", {
                                  "aria-hidden": true,
                                  className: "" + iconMenuClassNames + " h-6 w-6",
                                  fill: "none",
                                  stroke: "currentColor",
                                  strokeWidth: "1.5",
                                  viewBox: "0 0 24 24"
                                }, React.createElement("path", {
                                      d: "M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5",
                                      strokeLinecap: "round",
                                      strokeLinejoin: "round"
                                    })), React.createElement("svg", {
                                  "aria-hidden": true,
                                  className: "" + (
                                    isOpen ? "block" : "hidden"
                                  ) + " h-6 w-6",
                                  fill: "none",
                                  stroke: "currentColor",
                                  strokeWidth: "1.5",
                                  viewBox: "0 0 24 24"
                                }, React.createElement("path", {
                                      d: "M6 18L18 6M6 6l12 12",
                                      strokeLinecap: "round",
                                      strokeLinejoin: "round"
                                    })))), React.createElement("div", {
                          className: "flex flex-1 items-center justify-center sm:items-stretch sm:justify-start"
                        }, React.createElement("div", {
                              className: "flex flex-shrink-0 items-center"
                            }, React.createElement("img", {
                                  className: "block h-8 wAuto lg:hidden",
                                  alt: "Your Company",
                                  src: "https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                                }), React.createElement("img", {
                                  className: "hidden h-8 wAuto lg:block",
                                  alt: "Your Company",
                                  src: "https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                                })), React.createElement("div", {
                              className: "hidden sm:ml-6 sm:flex sm:space-x-8"
                            }, React.createElement(ActiveLink.make, {
                                  href: "/",
                                  children: "Home"
                                }), React.createElement(ActiveLink.make, {
                                  href: "/despedida",
                                  children: "Despedida"
                                }), React.createElement(ActiveLink.make, {
                                  href: "/courses",
                                  children: "Courses"
                                }), React.createElement(ActiveLink.make, {
                                  href: "/school",
                                  children: "Schools"
                                }))), React.createElement("div", {
                          className: "absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
                        }, React.createElement("button", {
                              className: "rounded-full bg-white p-1 text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                            }, React.createElement("span", {
                                  className: "sr-only"
                                }, "View notifications"), React.createElement("svg", {
                                  "aria-hidden": true,
                                  className: "h-6 w-6",
                                  fill: "none",
                                  stroke: "currentColor",
                                  strokeWidth: "1.5",
                                  viewBox: "0 0 24 24"
                                }, React.createElement("path", {
                                      d: "M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0",
                                      strokeLinecap: "round",
                                      strokeLinejoin: "round"
                                    }))), React.createElement("div", {
                              className: "relative ml-3"
                            }, React.createElement("div", {
                                  onClick: (function (param) {
                                      Curry._1(setIsOpen, (function (old) {
                                              return !old;
                                            }));
                                    })
                                }, React.createElement("button", {
                                      "aria-expanded": false,
                                      className: "flex rounded-full bg-white text-sm\n            focus:outline-none focus:ring-2 focus:ring-indigo-500\n            focus:ring-offset-2",
                                      id: "user-menuButton"
                                    }, React.createElement("span", {
                                          className: "sr-only"
                                        }, "Open user menu"), React.createElement("img", {
                                          className: "h-8 w-8 rounded-full",
                                          alt: "",
                                          src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                                        }))), React.createElement("div", {
                                  "aria-labelledby": "user-menuButton",
                                  className: "" + (
                                    isOpen ? "block" : "hidden"
                                  ) + " " + dropdownMenuClassNames + " absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none",
                                  role: "menu",
                                  tabIndex: -1
                                }, React.createElement("a", {
                                      className: "block px-4 py-2 text-sm text-gray-700",
                                      id: "user-menu-item-0",
                                      role: "menuitem",
                                      tabIndex: 1,
                                      href: "#"
                                    }, "Your Profile"), React.createElement("a", {
                                      className: "block px-4 py-2 text-sm text-gray-700",
                                      id: "user-menu-item-1",
                                      role: "menuitem",
                                      tabIndex: 1,
                                      href: "#"
                                    }, "Settings"), React.createElement("a", {
                                      className: "block px-4 py-2 text-sm text-gray-700",
                                      id: "user-menu-item-2",
                                      role: "menuitem",
                                      tabIndex: 1,
                                      href: "#"
                                    }, "Sign out")))))), React.createElement("div", {
                  className: "sm:hidden",
                  id: "mobile-menu"
                }, React.createElement("div", {
                      className: "space-y-1 pt-2 pb-4"
                    }, React.createElement("a", {
                          className: "block border-l-4 border-indigo-500 bg-indigo-50 py-2 pl-3 pr-4 text-base font-medium text-indigo-700",
                          href: "#"
                        }, "Dashboard"), React.createElement("a", {
                          className: "block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700",
                          href: "#"
                        }, "Team"), React.createElement("a", {
                          className: "block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700",
                          href: "#"
                        }, "Projects"), React.createElement("a", {
                          className: "block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700",
                          href: "#"
                        }, "Calendar"))));
}

var make = Navbar;

export {
  make ,
}
/* react Not a pure module */
