// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as MainLayout from "../../Layouts/MainLayout.bs.js";
import * as Router from "next/router";

function make(props) {
  var content = React.createElement(props.Component, props.pageProps);
  var router = Router.useRouter();
  var match = router.route;
  if (match === "/depedida") {
    return content;
  } else {
    return React.createElement(MainLayout.make, {
                children: content
              });
  }
}

export {
  make ,
}
/* react Not a pure module */
