// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Navbar from "../Components/Navbar/Navbar.bs.js";

function MainLayout(props) {
  console.log("test: manlayout");
  return React.createElement("main", {
              className: "w-full h-full"
            }, React.createElement(Navbar.make, {}), props.children);
}

var make = MainLayout;

export {
  make ,
}
/* react Not a pure module */
